# Generated by Django 2.2.12 on 2021-09-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
